title: Documentación Socio Unido
description: Documentación integral asociada al desarrollo del Trabajo Profesional "SocioUnido".
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/documentacion"
